// <auto-generated />
namespace kaaraoke_app.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddAudioFileIdToLRCFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAudioFileIdToLRCFile));
        
        string IMigrationMetadata.Id
        {
            get { return "202412240444245_AddAudioFileIdToLRCFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
